Make helper_method call public
Needed to move the helper_method call out of the private block to fix
error:
undefined local variable or method `current_theme'
in:
app/views/spina/admin/pages/index.html.haml:11